---
- name: AAA Config
  hosts: switch
  gather_facts: false

  vars:
    secret: "SECRET"
  tasks:
    - name: AAA
      ios_config:
        lines:
          - "aaa new-model"
          - "aaa authentication login default group tacacs+ local"
          - "aaa authentication enable default none"
          - "aaa authorization config-commands"
          - "aaa authorization exec default group tacacs+ local"
          - "aaa authorization exec ise group tacacs+ local"
          - "aaa authorization commands 0 default group tacacs+ local"
          - "aaa authorization commands 15 default group tacacs+ local" 
          - "aaa accounting update newinfo"
          - "aaa session-id common"
          - "ip http authentication aaa"
    - name: TACACS+
      ios_config:
        lines:
          - "address ipv4 172.20.0.10"
          - "key {{ secret }}"
        parents: tacacs server ise
