---
- name: AAA Config
  hosts: switch
  gather_facts: false

  vars:
    secret: "SECRET"
  tasks:
    - name: AAA
      ios_config:
        lines:
          - "aaa new-model"
          - "aaa authentication login default group tacacs+ local"
          - "aaa authentication enable default none"
          - "aaa authentication dot1x default group radius"
          - "aaa authorization config-commands"
          - "aaa authorization exec default group tacacs+ local"
          - "aaa authorization exec ise group tacacs+ local"
          - "aaa authorization commands 0 default group tacacs+ local"
          - "aaa authorization commands 15 default group tacacs+ local" 
          - "aaa authorization network default group radius"
          - "aaa accounting update newinfo"
          - "aaa accounting dot1x default start-stop group radius"
          - "aaa accounting system default start-stop group radius"
          - "aaa session-id common"
          - "ip http authentication aaa"

    - name: RADIUS COA
      ios_config:
        lines:
          - "client 172.20.0.10"
          - "server-key {{ secret }}"
        parents: aaa server radius dynamic-author

    - name: RADIUS
      ios_config:
        lines:
          - "address ipv4 172.20.0.10 auth-port 1812 acct-port 1813"
          - "key {{ secret }}"
        parents: radius server ise

    - name: TACACS+
      ios_config:
        lines:
          - "address ipv4 172.20.0.10"
          - "key {{ secret }}"
        parents: tacacs server ise
      tags:
        - test
    - name: Write Memory
      ios_config: 
        lines:
          - 'do write'
      tags:
        - test
