---
- name: Switchport-Security Configuration
  hosts: switch
  gather_facts: false

  vars:
    path_dir: "/root/ansible/cisco_ios/security/switchport-security/"
  pre_tasks:
    - name: Global DHCP Snooping
      ios_config:
        lines:
          - "ip dhcp snooping vlan 1-4094"
          - "ip dhcp snooping"
    
    - name: Prepare jinja2 Data
      shell: "hostname={{ path_dir }}/{{ inventory_hostname }}.data.yaml.0 hostname1={{ path_dir }}/{{ inventory_hostname }}.data.yaml.1 hostname2={{ path_dir }}/{{ inventory_hostname }}.data.yaml bash {{ path_dir }}/b2.sh"

    - name: Show running-config
      ios_command:
        commands: show running-config | sec interface
      register: config

    - name: Copy Config
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ path_dir }}/{{ inventory_hostname }}.data.yaml.0"

    - name: Create jinja2 Data
      shell: "hostname={{ path_dir }}/{{ inventory_hostname }}.data.yaml.0 hostname1={{ path_dir }}/{{ inventory_hostname }}.data.yaml.1 hostname2={{ path_dir }}/{{ inventory_hostname }}.data.yaml bash {{ path_dir }}/b1.sh"
  
  tasks:
    - include_vars: "{{ path_dir }}/{{ inventory_hostname }}.data.yaml"
    - name: AAA Port Configuration
      ios_config:
        src: template.j2

    - name: Delete jinja2 Data
      shell: "hostname={{ path_dir }}/{{ inventory_hostname }}.data.yaml.0 hostname1={{ path_dir }}/{{ inventory_hostname }}.data.yaml.1 hostname2={{ path_dir }}/{{ inventory_hostname }}.data.yaml bash {{ path_dir }}/b3.sh"
      